const boardEl=document.getElementById("board"),stageNameEl=document.getElementById("stageName"),moveCountEl=document.getElementById("moveCount"),selectedInfoEl=document.getElementById("selectedInfo"),remainCountEl=document.getElementById("remainCount"),messageEl=document.getElementById("message"),resetButton=document.getElementById("resetButton"),modalResetButton=document.getElementById("modalResetButton"),clearModal=document.getElementById("clearModal"),clearText=document.getElementById("clearText");
const DIRS={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}},MIN_CLEAR_VALUE=2;
const FACE_PRESETS={2:{top:2,bottom:5,north:1,south:6,west:3,east:4},3:{top:3,bottom:4,north:1,south:6,west:2,east:5},4:{top:4,bottom:3,north:1,south:6,west:5,east:2},5:{top:5,bottom:2,north:1,south:6,west:4,east:3},6:{top:6,bottom:1,north:2,south:5,west:3,east:4}};
const STAGES=[{name:"1-入口の間",size:7,grid:[["void","void","floor","floor","floor","void","void"],["void","floor","floor","floor","floor","floor","void"],["floor","floor","floor","floor","floor","floor","floor"],["floor","floor","floor","floor","floor","floor","floor"],["floor","floor","floor","floor","floor","floor","floor"],["void","floor","floor","floor","floor","floor","void"],["void","void","floor","floor","floor","void","void"]],diceValues:[2,2,3,3,3]},{name:"2-十字回廊",size:7,grid:[["void","void","void","floor","void","void","void"],["void","void","floor","floor","floor","void","void"],["void","floor","floor","floor","floor","floor","void"],["floor","floor","floor","floor","floor","floor","floor"],["void","floor","floor","floor","floor","floor","void"],["void","void","floor","floor","floor","void","void"],["void","void","void","floor","void","void","void"]],diceValues:[2,2,3,3,4,4]},{name:"3-欠けた広間",size:7,grid:[["void","floor","floor","floor","floor","floor","void"],["floor","floor","floor","void","floor","floor","floor"],["floor","floor","floor","floor","floor","floor","floor"],["floor","void","floor","floor","floor","void","floor"],["floor","floor","floor","floor","floor","floor","floor"],["floor","floor","floor","void","floor","floor","floor"],["void","floor","floor","floor","floor","floor","void"]],diceValues:[2,2,3,3,3,4,4]},{name:"4-輪の祭壇",size:7,grid:[["void","floor","floor","floor","floor","floor","void"],["floor","floor","floor","void","floor","floor","floor"],["floor","floor","void","void","void","floor","floor"],["floor","void","void","void","void","void","floor"],["floor","floor","void","void","void","floor","floor"],["floor","floor","floor","void","floor","floor","floor"],["void","floor","floor","floor","floor","floor","void"]],diceValues:[2,2,3,3,4,4,5]},{name:"5-深層の盤",size:8,grid:[["void","void","floor","floor","floor","floor","void","void"],["void","floor","floor","floor","floor","floor","floor","void"],["floor","floor","floor","void","floor","floor","floor","floor"],["floor","floor","void","floor","floor","void","floor","floor"],["floor","floor","floor","floor","void","floor","floor","floor"],["floor","floor","floor","void","floor","floor","floor","floor"],["void","floor","floor","floor","floor","floor","floor","void"],["void","void","floor","floor","floor","floor","void","void"]],diceValues:[2,2,3,3,3,4,4,5,5]}];
let currentStageIndex=0,grid=[],dice=[],selectedDiceId=null,moveCount=0,pointerStart=null,movingIds=new Map(),removingIds=new Set(),flashCells=[],isAnimating=false;
function initGame(){const s=STAGES[currentStageIndex];grid=s.grid.map(r=>r.map(type=>({type})));dice=createRandomDice(s);selectedDiceId=null;moveCount=0;pointerStart=null;movingIds.clear();removingIds.clear();flashCells=[];isAnimating=false;clearModal.classList.add("hidden");boardEl.style.setProperty("--size",s.size);stageNameEl.textContent=s.name;modalResetButton.textContent="次のステージへ";setMessage("ダイスを選んで転がそう。同じ上面の目が、その目の数以上つながると消える。");render()}
function createRandomDice(s){const floors=[];for(let y=0;y<s.grid.length;y++)for(let x=0;x<s.grid[y].length;x++)if(s.grid[y][x]==="floor")floors.push({x,y});for(let a=0;a<400;a++){const cells=shuffle([...floors]),res=s.diceValues.map((v,i)=>({id:String.fromCharCode(65+i),x:cells[i].x,y:cells[i].y,faces:{...FACE_PRESETS[v]}}));if(!hasInitialClearGroup(res))return res}const cells=shuffle([...floors]);return s.diceValues.map((v,i)=>({id:String.fromCharCode(65+i),x:cells[i].x,y:cells[i].y,faces:{...FACE_PRESETS[v]}}))}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function hasInitialClearGroup(list){const visited=new Set;for(const start of list){if(visited.has(start.id))continue;const value=start.faces.top,group=[],q=[start];visited.add(start.id);while(q.length){const c=q.shift();group.push(c);for(const o of list){if(visited.has(o.id)||o.faces.top!==value)continue;if(Math.abs(c.x-o.x)+Math.abs(c.y-o.y)===1){visited.add(o.id);q.push(o)}}}if(value>=MIN_CLEAR_VALUE&&group.length>=value)return true}return false}
function render(){boardEl.innerHTML="";moveCountEl.textContent=moveCount;remainCountEl.textContent=dice.length;const sel=dice.find(d=>d.id===selectedDiceId);selectedInfoEl.textContent=sel?`上面${sel.faces.top}`:"なし";for(let y=0;y<grid.length;y++)for(let x=0;x<grid[y].length;x++){const c=grid[y][x],cell=document.createElement("div");cell.classList.add("cell");if(c.type==="void")cell.classList.add("void");if(c.type==="floor")cell.classList.add("floor");if(c.type==="wall")cell.classList.add("wall");if(flashCells.some(p=>p.x===x&&p.y===y))cell.classList.add("match-flash");const die=dice.find(d=>d.x===x&&d.y===y);if(die){const e=document.createElement("div");e.classList.add("dice");e.dataset.id=die.id;if(die.id===selectedDiceId)e.classList.add("selected");if(movingIds.has(die.id))e.classList.add("moving",`move-${movingIds.get(die.id)}`);if(removingIds.has(die.id))e.classList.add("removing");e.appendChild(createDie(die.faces));e.addEventListener("click",()=>selectDice(die.id));e.addEventListener("pointerdown",onDicePointerDown);cell.appendChild(e)}boardEl.appendChild(cell)}}
function createDie(f){const b=document.createElement("div");b.classList.add("die-body");const top=document.createElement("div");top.classList.add("die-top");createPips(f.top).forEach(p=>top.appendChild(p));const front=document.createElement("div");front.classList.add("die-front");createPips(f.south).forEach(p=>front.appendChild(p.cloneNode(true)));const right=document.createElement("div");right.classList.add("die-right");createPips(f.east).forEach(p=>right.appendChild(p.cloneNode(true)));b.appendChild(right);b.appendChild(front);b.appendChild(top);return b}
function createPips(v){const m={1:["mc"],2:["tl","br"],3:["tl","mc","br"],4:["tl","tr","bl","br"],5:["tl","tr","mc","bl","br"],6:["tl","ml","bl","tr","mr","br"]};return(m[v]||["mc"]).map(pos=>{const p=document.createElement("span");p.classList.add("pip",pos);return p})}
function onDicePointerDown(ev){if(isAnimating)return;const id=ev.currentTarget.dataset.id;selectDice(id);pointerStart={x:ev.clientX,y:ev.clientY};ev.currentTarget.setPointerCapture(ev.pointerId);ev.currentTarget.addEventListener("pointerup",onDicePointerUp,{once:true})}
function onDicePointerUp(ev){if(isAnimating||!pointerStart||!selectedDiceId)return;const dx=ev.clientX-pointerStart.x,dy=ev.clientY-pointerStart.y,dist=Math.hypot(dx,dy);pointerStart=null;if(dist<26)return;moveSelected(Math.abs(dx)>Math.abs(dy)?dx>0?"right":"left":dy>0?"down":"up")}
function selectDice(id){if(isAnimating)return;selectedDiceId=id;const d=dice.find(x=>x.id===id);if(d)setMessage(`ダイス${d.id}を選択中。現在の上面は ${d.faces.top}。`);render()}
function moveSelected(dirName){if(isAnimating)return;const die=dice.find(d=>d.id===selectedDiceId);if(!die){setMessage("先にダイスをタップして選択してね。");shakeBoard();return}const dir=DIRS[dirName],nx=die.x+dir.x,ny=die.y+dir.y;if(!isInside(nx,ny)||grid[ny][nx].type==="void"||grid[ny][nx].type==="wall"){blockMove();return}if(dice.find(d=>d.x===nx&&d.y===ny)){setMessage("そのマスには別のダイスがある。");shakeBoard();return}isAnimating=true;movingIds.clear();flashCells=[];rollDiceFaces(die.faces,dirName);die.x=nx;die.y=ny;movingIds.set(die.id,dirName);moveCount++;render();setTimeout(()=>{movingIds.clear();const r=resolveMatchesFrom(die.id);if(r.removedIds.length>0){removingIds=new Set(r.removedIds);flashCells=r.positions;setMessage(`${r.removedIds.length}個のダイスが消える！`);render();setTimeout(()=>{dice=dice.filter(d=>!removingIds.has(d.id));if(selectedDiceId&&removingIds.has(selectedDiceId))selectedDiceId=null;removingIds.clear();flashCells=[];finishTurn()},280)}else finishTurn()},240)}
function finishTurn(){isAnimating=false;render();if(dice.length===0){const last=currentStageIndex===STAGES.length-1;clearText.textContent=last?`全5ステージクリア！ 移動回数：${moveCount}`:`ステージクリア！ 移動回数：${moveCount}`;modalResetButton.textContent=last?"最初から遊ぶ":"次のステージへ";clearModal.classList.remove("hidden");return}setMessage("次の一手を考えよう。1は消えない。")}
function nextStage(){currentStageIndex=currentStageIndex>=STAGES.length-1?0:currentStageIndex+1;initGame()}
function blockMove(){setMessage("そこには転がせない。");shakeBoard()}
function resolveMatchesFrom(id){const start=dice.find(d=>d.id===id);if(!start)return{removedIds:[],positions:[]};const value=start.faces.top;if(value<MIN_CLEAR_VALUE)return{removedIds:[],positions:[]};const visited=new Set([start.id]),q=[start],group=[];while(q.length){const c=q.shift();group.push(c);for(const o of dice){if(visited.has(o.id)||o.faces.top!==value)continue;if(Math.abs(c.x-o.x)+Math.abs(c.y-o.y)===1){visited.add(o.id);q.push(o)}}}if(group.length<value)return{removedIds:[],positions:[]};return{removedIds:group.map(d=>d.id),positions:group.map(d=>({x:d.x,y:d.y}))}}
function rollDiceFaces(f,dir){const o={...f};if(dir==="right"){f.top=o.west;f.bottom=o.east;f.east=o.top;f.west=o.bottom;f.north=o.north;f.south=o.south}if(dir==="left"){f.top=o.east;f.bottom=o.west;f.west=o.top;f.east=o.bottom;f.north=o.north;f.south=o.south}if(dir==="up"){f.top=o.south;f.bottom=o.north;f.north=o.top;f.south=o.bottom;f.east=o.east;f.west=o.west}if(dir==="down"){f.top=o.north;f.bottom=o.south;f.south=o.top;f.north=o.bottom;f.east=o.east;f.west=o.west}}
function isInside(x,y){return y>=0&&y<grid.length&&x>=0&&x<grid[y].length}
function setMessage(t){messageEl.textContent=t}
function shakeBoard(){boardEl.classList.remove("shake");void boardEl.offsetWidth;boardEl.classList.add("shake")}
document.querySelectorAll(".move-button").forEach(b=>b.addEventListener("click",()=>moveSelected(b.dataset.dir)));
resetButton.addEventListener("click",initGame);modalResetButton.addEventListener("click",nextStage);initGame();
