import * as THREE from "https://unpkg.com/three@0.160.0/build/three.module.js";

const $=id=>document.getElementById(id),sceneWrap=$("sceneWrap"),stageNameEl=$("stageName"),moveCountEl=$("moveCount"),selectedInfoEl=$("selectedInfo"),remainCountEl=$("remainCount"),messageEl=$("message"),resetButton=$("resetButton"),modalResetButton=$("modalResetButton"),clearModal=$("clearModal"),clearText=$("clearText");
const DIRS={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}},MIN_CLEAR_VALUE=2,CELL=0.92,DICE_SIZE=.56;
const FACE_PRESETS={2:{top:2,bottom:5,north:1,south:6,west:3,east:4},3:{top:3,bottom:4,north:1,south:6,west:2,east:5},4:{top:4,bottom:3,north:1,south:6,west:5,east:2},5:{top:5,bottom:2,north:1,south:6,west:4,east:3},6:{top:6,bottom:1,north:2,south:5,west:3,east:4}};
const STAGES=[{name:"1-入口の間",size:7,grid:[["void","void","floor","floor","floor","void","void"],["void","floor","floor","floor","floor","floor","void"],["floor","floor","floor","floor","floor","floor","floor"],["floor","floor","floor","floor","floor","floor","floor"],["floor","floor","floor","floor","floor","floor","floor"],["void","floor","floor","floor","floor","floor","void"],["void","void","floor","floor","floor","void","void"]],diceValues:[2,2,3,3,3]},{name:"2-十字回廊",size:7,grid:[["void","void","void","floor","void","void","void"],["void","void","floor","floor","floor","void","void"],["void","floor","floor","floor","floor","floor","void"],["floor","floor","floor","floor","floor","floor","floor"],["void","floor","floor","floor","floor","floor","void"],["void","void","floor","floor","floor","void","void"],["void","void","void","floor","void","void","void"]],diceValues:[2,2,3,3,4,4]},{name:"3-欠けた広間",size:7,grid:[["void","floor","floor","floor","floor","floor","void"],["floor","floor","floor","void","floor","floor","floor"],["floor","floor","floor","floor","floor","floor","floor"],["floor","void","floor","floor","floor","void","floor"],["floor","floor","floor","floor","floor","floor","floor"],["floor","floor","floor","void","floor","floor","floor"],["void","floor","floor","floor","floor","floor","void"]],diceValues:[2,2,3,3,3,4,4]},{name:"4-輪の祭壇",size:7,grid:[["void","floor","floor","floor","floor","floor","void"],["floor","floor","floor","void","floor","floor","floor"],["floor","floor","void","void","void","floor","floor"],["floor","void","void","void","void","void","floor"],["floor","floor","void","void","void","floor","floor"],["floor","floor","floor","void","floor","floor","floor"],["void","floor","floor","floor","floor","floor","void"]],diceValues:[2,2,3,3,4,4,5]},{name:"5-深層の盤",size:8,grid:[["void","void","floor","floor","floor","floor","void","void"],["void","floor","floor","floor","floor","floor","floor","void"],["floor","floor","floor","void","floor","floor","floor","floor"],["floor","floor","void","floor","floor","void","floor","floor"],["floor","floor","floor","floor","void","floor","floor","floor"],["floor","floor","floor","void","floor","floor","floor","floor"],["void","floor","floor","floor","floor","floor","floor","void"],["void","void","floor","floor","floor","floor","void","void"]],diceValues:[2,2,3,3,3,4,4,5,5]}];

let currentStageIndex=0,grid=[],dice=[],selectedDiceId=null,moveCount=0,isAnimating=false,rolling=null,selectedRing=null;
let scene,camera,renderer,boardGroup,diceGroup,raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
const matTile=new THREE.MeshStandardMaterial({color:0x33406f,roughness:.72,metalness:.02}),matTile2=new THREE.MeshStandardMaterial({color:0x222b55,roughness:.85}),matLine=new THREE.LineBasicMaterial({color:0x9fb2ff,transparent:true,opacity:.35});

initThree();initGame();animate();

function initThree(){scene=new THREE.Scene();scene.background=null;camera=new THREE.PerspectiveCamera(38,sceneWrap.clientWidth/sceneWrap.clientHeight,.1,100);renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(sceneWrap.clientWidth,sceneWrap.clientHeight);renderer.shadowMap.enabled=true;sceneWrap.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x24305a,2.4));const d=new THREE.DirectionalLight(0xffffff,2.2);d.position.set(4,8,5);d.castShadow=true;scene.add(d);boardGroup=new THREE.Group();diceGroup=new THREE.Group();scene.add(boardGroup,diceGroup);selectedRing=new THREE.Mesh(new THREE.RingGeometry(.38,.47,48),new THREE.MeshBasicMaterial({color:0xffd94f,transparent:true,opacity:.75,side:THREE.DoubleSide}));selectedRing.rotation.x=-Math.PI/2;selectedRing.visible=false;scene.add(selectedRing);renderer.domElement.addEventListener("pointerdown",onCanvasPointer);addEventListener("resize",resizeThree)}
function resizeThree(){camera.aspect=sceneWrap.clientWidth/sceneWrap.clientHeight;camera.updateProjectionMatrix();renderer.setSize(sceneWrap.clientWidth,sceneWrap.clientHeight)}
function setCamera(size){const s=size*CELL;camera.position.set(s*.72,s*.95,s*1.05);camera.lookAt(0,0,0)}
function worldPos(x,y){const s=STAGES[currentStageIndex].size,c=(s-1)/2;return new THREE.Vector3((x-c)*CELL,.38,(y-c)*CELL)}
function initGame(){const st=STAGES[currentStageIndex];grid=st.grid.map(r=>r.map(type=>({type})));dice=createRandomDice(st);selectedDiceId=null;moveCount=0;isAnimating=false;rolling=null;clearModal.classList.add("hidden");stageNameEl.textContent=st.name;modalResetButton.textContent="次のステージへ";setCamera(st.size);buildBoard(st);buildDice();setMessage("ダイスを選んで転がそう。同じ上面の目が、その目の数以上つながると消える。");updateHud()}
function clearGroup(g){while(g.children.length){const o=g.children.pop();o.traverse?.(c=>{c.geometry?.dispose?.();if(Array.isArray(c.material))c.material.forEach(m=>m.dispose?.());else c.material?.dispose?.()})}}
function buildBoard(st){clearGroup(boardGroup);const geo=new THREE.BoxGeometry(CELL*.82,.08,CELL*.82),edgeGeo=new THREE.EdgesGeometry(geo);for(let y=0;y<st.grid.length;y++)for(let x=0;x<st.grid[y].length;x++){if(st.grid[y][x]!=="floor")continue;const p=worldPos(x,y),m=new THREE.Mesh(geo,(x+y)%2?matTile:matTile2);m.position.set(p.x,0,p.z);m.receiveShadow=true;boardGroup.add(m);const e=new THREE.LineSegments(edgeGeo,matLine);e.position.copy(m.position);boardGroup.add(e)}}
function buildDice(){clearGroup(diceGroup);for(const d of dice){d.group=createDieGroup(d);diceGroup.add(d.group)}updateSelection()}
function createDieGroup(d){const g=new THREE.Group();g.userData.dieId=d.id;const mesh=new THREE.Mesh(new THREE.BoxGeometry(DICE_SIZE,DICE_SIZE,DICE_SIZE),makeDiceMaterials(d.faces));mesh.castShadow=true;mesh.userData.dieId=d.id;g.add(mesh);const edges=new THREE.LineSegments(new THREE.EdgesGeometry(mesh.geometry),new THREE.LineBasicMaterial({color:0xffffff,transparent:true,opacity:.5}));edges.userData.dieId=d.id;g.add(edges);g.position.copy(worldPos(d.x,d.y));return g}
function makeDiceMaterials(f){return [faceMat(f.east),faceMat(f.west),faceMat(f.top),faceMat(f.bottom),faceMat(f.south),faceMat(f.north)]}
function faceMat(v){const c=document.createElement("canvas"),s=128,ctx=c.getContext("2d");c.width=c.height=s;const grd=ctx.createLinearGradient(0,0,s,s);grd.addColorStop(0,"#fff");grd.addColorStop(.58,"#eaf0ff");grd.addColorStop(1,"#b7c7ff");ctx.fillStyle=grd;round(ctx,4,4,s-8,s-8,18);ctx.fill();ctx.strokeStyle="rgba(120,140,190,.55)";ctx.lineWidth=5;ctx.stroke();ctx.fillStyle="#071026";const pos={tl:[34,34],tc:[64,34],tr:[94,34],ml:[34,64],mc:[64,64],mr:[94,64],bl:[34,94],bc:[64,94],br:[94,94]},map={1:["mc"],2:["tl","br"],3:["tl","mc","br"],4:["tl","tr","bl","br"],5:["tl","tr","mc","bl","br"],6:["tl","ml","bl","tr","mr","br"]};for(const key of map[v]||["mc"]){const [x,y]=pos[key];ctx.beginPath();ctx.arc(x,y,8,0,Math.PI*2);ctx.fill()}const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;return new THREE.MeshStandardMaterial({map:tex,roughness:.48,metalness:.02})}
function round(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function updateDieMaterials(d){const mesh=d.group.children[0];mesh.material.forEach(m=>m.dispose());mesh.material=makeDiceMaterials(d.faces)}
function createRandomDice(st){const floors=[];for(let y=0;y<st.grid.length;y++)for(let x=0;x<st.grid[y].length;x++)if(st.grid[y][x]==="floor")floors.push({x,y});for(let a=0;a<400;a++){const cells=shuffle([...floors]),res=st.diceValues.map((v,i)=>({id:String.fromCharCode(65+i),x:cells[i].x,y:cells[i].y,faces:{...FACE_PRESETS[v]}}));if(!hasInitialClearGroup(res))return res}const cells=shuffle([...floors]);return st.diceValues.map((v,i)=>({id:String.fromCharCode(65+i),x:cells[i].x,y:cells[i].y,faces:{...FACE_PRESETS[v]}}))}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function hasInitialClearGroup(list){const visited=new Set;for(const s of list){if(visited.has(s.id))continue;const value=s.faces.top,g=[],q=[s];visited.add(s.id);while(q.length){const c=q.shift();g.push(c);for(const o of list){if(visited.has(o.id)||o.faces.top!==value)continue;if(Math.abs(c.x-o.x)+Math.abs(c.y-o.y)===1){visited.add(o.id);q.push(o)}}}if(value>=MIN_CLEAR_VALUE&&g.length>=value)return true}return false}
function updateHud(){moveCountEl.textContent=moveCount;remainCountEl.textContent=dice.length;const s=dice.find(d=>d.id===selectedDiceId);selectedInfoEl.textContent=s?`上面${s.faces.top}`:"なし"}
function onCanvasPointer(e){if(isAnimating)return;const r=renderer.domElement.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(diceGroup.children,true);if(!hits.length)return;let o=hits[0].object;while(o&&!o.userData.dieId)o=o.parent;if(o?.userData.dieId)selectDice(o.userData.dieId)}
function selectDice(id){if(isAnimating)return;selectedDiceId=id;const d=dice.find(x=>x.id===id);setMessage(`ダイス${id}を選択中。現在の上面は ${d.faces.top}。`);updateSelection();updateHud()}
function updateSelection(){const d=dice.find(x=>x.id===selectedDiceId);if(!d){selectedRing.visible=false;return}selectedRing.visible=true;const p=worldPos(d.x,d.y);selectedRing.position.set(p.x,.08,p.z)}
function moveSelected(dirName){if(isAnimating)return;const d=dice.find(x=>x.id===selectedDiceId);if(!d){setMessage("先にダイスを選択してね。");return}const dir=DIRS[dirName],nx=d.x+dir.x,ny=d.y+dir.y;if(!isInside(nx,ny)||grid[ny][nx].type!=="floor"){setMessage("そこには転がせない。");return}if(dice.some(o=>o.id!==d.id&&o.x===nx&&o.y===ny)){setMessage("そのマスには別のダイスがある。");return}isAnimating=true;rolling={die:d,dirName,from:worldPos(d.x,d.y),to:worldPos(nx,ny),nx,ny,start:performance.now(),dur:330};selectedRing.visible=false;moveCount++;updateHud()}
function completeRoll(){const r=rolling,d=r.die;d.x=r.nx;d.y=r.ny;rollDiceFaces(d.faces,r.dirName);d.group.position.copy(r.to);d.group.rotation.set(0,0,0);updateDieMaterials(d);rolling=null;const res=resolveMatchesFrom(d.id);if(res.removedIds.length){setMessage(`${res.removedIds.length}個のダイスが消える！`);setTimeout(()=>{for(const id of res.removedIds){const idx=dice.findIndex(x=>x.id===id);if(idx>=0){diceGroup.remove(dice[idx].group);dice.splice(idx,1)}}if(selectedDiceId&&!dice.some(x=>x.id===selectedDiceId))selectedDiceId=null;finishTurn()},180)}else finishTurn()}
function finishTurn(){isAnimating=false;updateSelection();updateHud();if(!dice.length){const last=currentStageIndex===STAGES.length-1;clearText.textContent=last?`全5ステージクリア！ 移動回数：${moveCount}`:`ステージクリア！ 移動回数：${moveCount}`;modalResetButton.textContent=last?"最初から遊ぶ":"次のステージへ";clearModal.classList.remove("hidden");return}setMessage("次の一手を考えよう。1は消えない。")}
function resolveMatchesFrom(id){const start=dice.find(d=>d.id===id);if(!start)return{removedIds:[]};const value=start.faces.top;if(value<MIN_CLEAR_VALUE)return{removedIds:[]};const visited=new Set([start.id]),q=[start],group=[];while(q.length){const c=q.shift();group.push(c);for(const o of dice){if(visited.has(o.id)||o.faces.top!==value)continue;if(Math.abs(c.x-o.x)+Math.abs(c.y-o.y)===1){visited.add(o.id);q.push(o)}}}return group.length>=value?{removedIds:group.map(d=>d.id)}:{removedIds:[]}}
function rollDiceFaces(f,dir){const o={...f};if(dir==="right"){f.top=o.west;f.bottom=o.east;f.east=o.top;f.west=o.bottom}if(dir==="left"){f.top=o.east;f.bottom=o.west;f.west=o.top;f.east=o.bottom}if(dir==="up"){f.top=o.south;f.bottom=o.north;f.north=o.top;f.south=o.bottom}if(dir==="down"){f.top=o.north;f.bottom=o.south;f.south=o.top;f.north=o.bottom}}
function animate(){requestAnimationFrame(animate);if(rolling){const t=Math.min(1,(performance.now()-rolling.start)/rolling.dur),p=1-Math.pow(1-t,3),d=rolling.die;d.group.position.lerpVectors(rolling.from,rolling.to,p);d.group.position.y=.38+Math.sin(p*Math.PI)*.28;const a=p*Math.PI/2;d.group.rotation.set(0,0,0);if(rolling.dirName==="right")d.group.rotation.z=-a;if(rolling.dirName==="left")d.group.rotation.z=a;if(rolling.dirName==="down")d.group.rotation.x=a;if(rolling.dirName==="up")d.group.rotation.x=-a;if(t>=1)completeRoll()}renderer.render(scene,camera)}
function nextStage(){currentStageIndex=currentStageIndex>=STAGES.length-1?0:currentStageIndex+1;initGame()}
function isInside(x,y){return y>=0&&y<grid.length&&x>=0&&x<grid[y].length}
function setMessage(t){messageEl.textContent=t}
document.querySelectorAll(".move-button").forEach(b=>b.addEventListener("click",()=>moveSelected(b.dataset.dir)));
resetButton.addEventListener("click",initGame);modalResetButton.addEventListener("click",nextStage);
